import type { Metadata } from "next";

import { Montserrat } from "next/font/google";

import "@/styles/globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--ff-montserrat",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.variable}>{children}</body>
    </html>
  );
}
