import '@/styles/globals.css';
import { type Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { tv } from 'tailwind-variants';

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--ff-montserrat',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

const body = tv({
  base: `${montserrat.variable} font-sans`,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={body()}>{children}</body>
    </html>
  );
}
